#!/bin/bash

########################################
# Choose kernel arch
KERNEL_ARCH=x86

echo $1
while ! [ -z $1 ]
do
	case $1 in
		"64" )
			KERNEL_ARCH=x86_64
			;;
		"clean" )
			NEED_CLEAN=clean
			;;
		* )
			;;
	esac

	shift
done

########################################

KERNEL_VERSION=`make kernelversion | cut -d "." -f1-2`

KERNEL_SOURCE_DIR=`basename $PWD`

KERNEL_OUT=/out/kernel/$KERNEL_ARCH/$KERNEL_SOURCE_DIR

#KERNEL_TOOLCHAIN=/data/leesheen/workdir/phoenixOS/x86/marshmallow/beta/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/bin/x86_64-linux-android-

KERNEL_CONFIG=android-"$KERNEL_ARCH"_defconfig

echo $KERNEL_OUT
echo $KERNEL_CONFIG

########################################

#KERNEL_MAKE="make O=$KERNEL_OUT ARCH=x86 CROSS_COMPILE=$KERNEL_TOOLCHAIN"
KERNEL_MAKE="make O=$KERNEL_OUT ARCH=$KERNEL_ARCH"

$KERNEL_MAKE $KERNEL_CONFIG
$KERNEL_MAKE menuconfig
