#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

# for fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
#export TERM=xterm-256color
#xbindkeys 
fcitx &
#exec startxfce4
feh --bg-scale /home/leesheen/Documents/thinkpad-dark.jpg
exec i3

# Here Xfce is kept as default
#session=${1:-xfce}
#
#case $session in
#    xfce|xfce4        ) exec startxfce4;;
#    i3|i3wm           ) exec i3;;
#    awesome           ) exec awesome;;
#    bspwm             ) exec bspwm;;
#    catwm             ) exec catwm;;
#    cinnamon          ) exec cinnamon-session;;
#    dwm               ) exec dwm;;
#    enlightenment     ) exec enlightenment_start;;
#    ede               ) exec startede;;
#    fluxbox           ) exec startfluxbox;;
#    gnome             ) exec gnome-session;;
#    gnome-classic     ) exec gnome-session --session=gnome-classic;;
#    icewm             ) exec icewm-session;;
#    jwm               ) exec jwm;;
#    kde               ) exec startkde;;
#    mate              ) exec mate-session;;
#    monster|monsterwm ) exec monsterwm;;
#    notion            ) exec notion;;
#    openbox           ) exec openbox-session;;
#    unity             ) exec unity;;
#    xmonad            ) exec xmonad;;
    # No known session, try to run it as command
#    *) exec $1;;
#esac
