# Path to your oh-my-zsh installation.
  export ZSH=/home/leesheen/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git repo sudo cp extract colorize autojump zsh-autosuggestions)

# User configuration

export PATH="/home/leesheen/tools/config-linux/script/work:/home/leesheen/tools/config-linux/tools/depot_tools:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# added by leesheen
# Apps
alias pcs='proxychains4 -q'

# Dirs
alias cdwo='cd ~/workdir/'
alias cdk='cd ~/workdir/linux/kernel'
alias cdos='cd ~/workdir/android'
alias cdlollbetaos='cd ~/workdir/android/x86/phoenixOS-lollipop'
alias cdbetaos='cd ~/workdir/android/x86/phoenixOS-marshmallow'
alias cdnativeos='cd ~/workdir/android/x86/x86-marshmallow'
alias cdout='cd out/target/product/'
alias cdlog='cd ~/workdir/log/'

# Files
alias -s xz='tar xvf'
alias -s bz2='tar xvf'
alias -s gz='tar xvf'
alias -s zip='unzip'
alias -s rar='unrar'
alias -s 7z='7za x'
alias -s c='vim'
alias -s cc='vim'
alias -s S='vim'
alias -s cpp='vim'
alias -s h='vim'

# make 
alias makekv='make kernelversion'

# other
alias retsave='~/tools/config-linux/script/work/shellreturn.sh -s'
alias retpop='~/tools/config-linux/script/work/shellreturn.sh -p'

# Powerline
#powerline-daemon -q

# autojump
[[ -s /home/leesheen/.autojump/etc/profile.d/autojump.sh ]] && source /home/leesheen/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u

#export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'
export ANDROID_HOME=/opt/android-sdk
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=$(which python3)
